# Generated by Django 3.2 on 2021-06-23 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.CharField(blank=True, max_length=45, null=True)),
                ('max', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'address_table',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('address_table', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.addresstable')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('product', models.ForeignKey(blank=True, db_column='Product_id', on_delete=django.db.models.deletion.CASCADE, to='warehouse.product')),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='StorageBin',
            fields=[
                ('address', models.IntegerField(primary_key=True, serialize=False)),
                ('size', models.CharField(blank=True, max_length=45, null=True)),
                ('type', models.ForeignKey(blank=True, db_column='Type_id', on_delete=django.db.models.deletion.CASCADE, to='warehouse.type')),
                ('warehouse', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'storage_bin',
            },
        ),
        migrations.AddField(
            model_name='addresstable',
            name='storage_bin_address',
            field=models.ForeignKey(blank=True, db_column='storage_bin_address', on_delete=django.db.models.deletion.CASCADE, to='warehouse.storagebin'),
        ),
    ]
