# Generated by Django 3.2 on 2021-06-23 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstable',
            name='storage_bin_address',
            field=models.ForeignKey(blank=True, db_column='storage_bin_address', null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.storagebin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='address_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.addresstable'),
        ),
        migrations.AlterField(
            model_name='storagebin',
            name='type',
            field=models.ForeignKey(blank=True, db_column='Type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.type'),
        ),
        migrations.AlterField(
            model_name='storagebin',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse'),
        ),
        migrations.AlterField(
            model_name='type',
            name='product',
            field=models.ForeignKey(blank=True, db_column='Product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.product'),
        ),
    ]
