# Generated by Django 3.2 on 2021-06-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20210623_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='address_table',
            field=models.ForeignKey(blank=True, default=452.2, on_delete=django.db.models.deletion.CASCADE, to='warehouse.addresstable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storagebin',
            name='type',
            field=models.ForeignKey(blank=True, db_column='Type_id', on_delete=django.db.models.deletion.CASCADE, to='warehouse.type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='product',
            field=models.ForeignKey(blank=True, db_column='Product_id', default=2020.3, on_delete=django.db.models.deletion.CASCADE, to='warehouse.product'),
            preserve_default=False,
        ),
    ]
